#!/bin/bash

pip3 install -U powerline-status $* || exit

if ! grep powerline ~/.bashrc &>/dev/null; then
PLSH=`find /usr/ /lib/ ~/.local -name powerline.sh |grep bash`
echo "found $PLSH"
cat <<EOF >>~/.bashrc
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. $PLSH
EOF
fi

if ! grep powerline ~/.vimrc &>/dev/null; then
cat <<EOF >>~/.vimrc
python3 from powerline.vim import setup as powerline_setup
python3 powerline_setup()
python3 del powerline_setup
set laststatus=2 " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
set t_Co=256
EOF
fi

if ! grep powerline ~/.tmux.conf &>/dev/null; then
PLSH=`find /usr/ /lib/ ~/.local -name powerline.conf |grep tmux`
echo "found $PLSH"
cat <<EOF >>~/.tmux.conf
source $PLSH
set-option -g default-terminal "screen-256color"
EOF
cat ~/.tmux.conf >>~/.byobu/.tmux.conf
fi

if ! grep powerline ~/.tmux.conf &>/dev/null; then
PLSH=`find /usr/ /lib/ ~/.local -name powerline.conf |grep tmux`
echo "found $PLSH"
cat <<EOF >>~/.tmux.conf
source $PLSH
set-option -g default-terminal "screen-256color"
EOF
cat ~/.tmux.conf >>~/.byobu/.tmux.conf
fi

if ! grep powerline ~/.config/fish/config.fish &>/dev/null; then
PLSH=`find /usr/ /lib/ ~/.local -name fish |grep powerline/bindings`
echo "found $PLSH"
cat <<EOF >>~/.config/fish/config.fish
set fish_function_path \$fish_function_path $PLSH
powerline-setup
EOF
fi

find /usr/ /lib/ ~/.local -name config.json |grep powerline
