#!/bin/bash

# simple script to update dyndns entries on https://www.regfish.de/

APIDOC="https://www.regfish.de/domains/dyndns/dokumentation"
IPURL="http://www.regfish.de/show_myip.php"

# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
OTHER=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -t|--token)
      TOKEN=$2
      shift 2
    ;;
    -l|--ttl)
      TTL=$2
      shift 2
    ;;
    -f|--force)
      FORCE=1
      shift
    ;;
    -F)
      CHANGED=1
      shift
    ;;
    -v)
      VERBOSE=1
      shift
    ;;
    -4)
      IPVERSION="${IPVERSION}4 "
      shift
    ;;
    -6)
      IPVERSION="${IPVERSION}6 "
      shift
    ;;
    -*)
      echo "unknown option: $1"
      exit 1
    ;;
    *)
      OTHER+=("$1")
      shift
    ;;
  esac
done
set -- "${OTHER[@]}" # restore positionals
DOMAINS="$@"

if [[ $# < 1 ]]; then
cat <<EOF
usage: $0 [options] -t TOKEN FQDN...

version 2019-02-22

positional args:
  FQDN             fully qualified domain name, ending in .

options:
  -t,--token       authentication token (required)
  -l,--ttl         TTL (600)
  -f,--force       force creation of DNS entry (no)
  -F               force update, even if unchanged (no)
  -4               use IPv4 address (yes)
  -6               use IPv6 address (yes)

see also $APIDOC
EOF
exit
fi

################################################################################

if [[ $VERBOSE ]]; then
  function log {
    echo "$@"
  }
else
  function log { :; }
fi

IPVERSION=${IPVERSION:-4 6}

for FQDN in $DOMAINS; do
  IPFILE="/run/shm/regfish/$FQDN"
  URL="https://dyndns.regfish.de/?token=${TOKEN}&fqdn=${FQDN}&forcehost=${FORCE:-0}&ttl=${TTL:-600}"

  function getip {
    curl -sL$1 $IPURL
  }

  function unchanged {
    grep "$1" $IPFILE &>/dev/null
  }

  unset IPS
  for V in $IPVERSION; do
    IP=`getip $V`
    if [[ $IP ]]; then
      unchanged $IP || CHANGED=1
      IPS="$IPS$IP "
      URL="$URL&ipv$V=$IP"
    fi
  done

  log "FQDN=$FQDN"
  log "IPVERSION=$IPVERSION"
  log "IPS=$IPS"
  log "IPFILE=$IPFILE"
  log "CHANGED=$CHANGED"

  [[ -z $CHANGED ]] && continue

  log "$URL"

  RESPONSE=`curl -sL "$URL"`

  log "$? - $RESPONSE"

  if [[ $RESPONSE == *success* ]]; then
    mkdir ${IPFILE%/*} &>/dev/null
    echo "$IPS" >$IPFILE
  else
    echo $RESPONSE
  fi

done
